idle_bg = "#282a3699"
idle_fg = "#f8f8f2dd"
info_bg = "#8be9fd99"
info_fg = "#282a36dd"
good_bg = "#50fa7b99"
good_fg = "#282a36dd"
warning_bg = "#f1fa8c99"
warning_fg = "#282a36dd"
critical_bg = "#ff555599"
critical_fg = "#282a36dd"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#11111100"
alternating_tint_fg = "#11111100"
