idle_bg = "#42424299"
idle_fg = "#ffffffdd"
info_bg = "#2196f399"
info_fg = "#ffffffdd"
good_bg = "#8bc34a99"
good_fg = "#000000dd"
warning_bg = "#ffc10799"
warning_fg = "#000000dd"
critical_bg = "#f4433699"
critical_fg = "#ffffffdd"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#11111100"
alternating_tint_fg = "#11111100"
