idle_bg = "#06060f99"             # Rich black
idle_fg = "#c1c1c1dd"             # Silver
info_bg = "#00223f9e"             # Maastricht Blue
info_fg = "#c1c1c1dd"             # Silver
good_bg = "#3940499e"             # Arsenic
good_fg = "#c1c1c1dd"             # Silver
warning_bg = "#2d1637ee"          # Dark Purple
warning_fg = "#c1c1c1dd"          # Silver
critical_bg = "#4d152b99"         # Silver
critical_fg = "#c1c1c1dd"         # Dark Purple
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
alternating_tint_bg = "#11111100"
alternating_tint_fg = "#11111100"
