#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME" || exit

# Make expected directories
mkdir -p ~/.local/bin
mkdir -p ~/git/github.com/

git clone ssh://git@github.com/soupersauce/anvil ~/.config/nvim
git clone https://github.com/ohmyzsh/ohmyzsh ~/.oh-my-zsh
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone https://github.com/romkatv/powerlevel10k ~/.oh-my-zsh/custom/themes/powerlevel10k
git clone https://github.com/ttys3/starship-config/ ~/git/github.com/ttys3/starship-config/
git clone https://github.com/jluttine/rofi-power-menu ~/git/github.com/rofi-power-menu/
cp ~/git/github.com/rofi-power-menu/rofi-power-menu ~/.local/bin/
chmod +x ~/.local/bin/rofi-power-menu
cd ~/git/github.com/ttys3/starship-config/os-icon/ && go build && cd "$HOME"
cp ~/git/github.com/ttys3/starship-config/os-icon/os-icon ~/.local/bin
git clone https://github.com/junegunn/fzf ~/.fzf
~/.fzf/install --completion --key-bindings --update-rc
